FROM node:14

WORKDIR /app

COPY package*.json ./

RUN apt-get update && apt-get install -y curl kafkacat && rm -rf /var/lib/apt/lists/*
RUN npm install
RUN npm install @graphql-tools/merge@latest @graphql-tools/mock@latest kafkajs sequelize mariadb mysql2

COPY . .

ENV PORT=8003
ENV KAFKA_MESSAGE_MAX_BYTES=200000000
ENV KAFKA_FETCH_MAX_BYTES=200000000

COPY wait-for.sh /usr/local/bin/wait-for.sh
RUN chmod +x /usr/local/bin/wait-for.sh

CMD ["wait-for.sh", "kafka", "node", "src/evenement.js"]
