apiVersion: apps/v1
kind: Deployment
metadata:
  name: profilmusical-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profilmusical-db
  template:
    metadata:
      labels:
        app: profilmusical-db
    spec:
      containers:
        - name: profilmusical-db
          image: profilmusicaldb:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "admin"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: utilisateur-db
spec:
  selector:
    app: utilisateur-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
